/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.23
 * Generated at: 2026-06-28 15:05:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    if (session != null && session.getAttribute("userId") != null) {
        response.sendRedirect(request.getContextPath() + "/chat");
        return;
    }

    String error = request.getParameter("error");
    String registered = request.getParameter("registered");
    String deleted = request.getParameter("deleted");
    String noticeText = null;
    if ("1".equals(registered)) {
        noticeText = "Registration completed successfully. You can sign in now.";
    } else if ("1".equals(deleted)) {
        noticeText = "Account deleted successfully.";
    } else if ("invalid".equals(error) || "1".equals(error)) {
        noticeText = "Invalid username or password.";
    } else if ("account_delete_failed".equals(error)) {
        noticeText = "Account could not be deleted. Try again.";
    }
    String contextPath = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Login | TeamConnect</title>\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&family=Inter:wght@300;400;500;600;700&display=swap');\n");
      out.write("\n");
      out.write("        :root {\n");
      out.write("            --bg:            #020818;\n");
      out.write("            --bg-2:          #030E22;\n");
      out.write("            --text:          #F1F5F9;\n");
      out.write("            --muted:         #94A3B8;\n");
      out.write("            --muted-dim:     #64748B;\n");
      out.write("            --border:        rgba(59, 130, 246, 0.16);\n");
      out.write("            --shadow:        0 28px 72px rgba(0, 0, 0, 0.65);\n");
      out.write("            --blue:          #2563EB;\n");
      out.write("            --blue-mid:      #3B82F6;\n");
      out.write("            --blue-light:    #60A5FA;\n");
      out.write("            --blue-glow:     #93C5FD;\n");
      out.write("            --silver:        #CBD5E1;\n");
      out.write("            --silver-dim:    #94A3B8;\n");
      out.write("            --silver-bright: #F1F5F9;\n");
      out.write("            --success:       #34D399;\n");
      out.write("            --danger:        #F87171;\n");
      out.write("            --grad-text:     linear-gradient(120deg, #F1F5F9 10%, #93C5FD 50%, #60A5FA 90%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * { box-sizing: border-box; }\n");
      out.write("\n");
      out.write("        html, body {\n");
      out.write("            margin: 0; min-height: 100%;\n");
      out.write("            font-family: 'Inter', 'Segoe UI', Arial, sans-serif;\n");
      out.write("            color: var(--text);\n");
      out.write("            background: var(--bg);\n");
      out.write("            overflow-x: hidden;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            background:\n");
      out.write("                    radial-gradient(ellipse 90% 60% at 8% -10%, rgba(37,99,235,0.26) 0%, transparent 52%),\n");
      out.write("                    radial-gradient(ellipse 70% 55% at 94%  8%, rgba(96,165,250,0.15) 0%, transparent 48%),\n");
      out.write("                    radial-gradient(ellipse 75% 55% at 50% 112%, rgba(59,130,246,0.11) 0%, transparent 55%),\n");
      out.write("                    linear-gradient(180deg, #020818 0%, #030D20 55%, #020818 100%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Aurora */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\"; position: fixed; inset: 0; z-index: 0; pointer-events: none;\n");
      out.write("            background:\n");
      out.write("                    radial-gradient(ellipse 680px 400px at 12% 22%, rgba(37,99,235,0.09) 0%, transparent 70%),\n");
      out.write("                    radial-gradient(ellipse 540px 360px at 88% 78%, rgba(96,165,250,0.07) 0%, transparent 70%);\n");
      out.write("            animation: auroraShift 22s ease-in-out infinite alternate;\n");
      out.write("        }\n");
      out.write("        @keyframes auroraShift {\n");
      out.write("            0%   { transform: translate(0,0) scale(1); }\n");
      out.write("            50%  { transform: translate(-28px,18px) scale(1.05); }\n");
      out.write("            100% { transform: translate(22px,-26px) scale(0.97); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Grid */\n");
      out.write("        body::after {\n");
      out.write("            content: \"\"; position: fixed; inset: 0; z-index: 0; pointer-events: none;\n");
      out.write("            background-image:\n");
      out.write("                    linear-gradient(rgba(59,130,246,0.045) 1px, transparent 1px),\n");
      out.write("                    linear-gradient(90deg, rgba(59,130,246,0.045) 1px, transparent 1px);\n");
      out.write("            background-size: 70px 70px;\n");
      out.write("            mask-image: radial-gradient(ellipse 85% 75% at 50% 50%, black 15%, transparent 80%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        a { color: inherit; text-decoration: none; }\n");
      out.write("\n");
      out.write("        .page { min-height: 100vh; padding: 18px; position: relative; z-index: 1; }\n");
      out.write("\n");
      out.write("        .shell {\n");
      out.write("            width: min(1180px, 100%);\n");
      out.write("            min-height: calc(100vh - 36px);\n");
      out.write("            margin: 0 auto;\n");
      out.write("            display: grid;\n");
      out.write("            grid-template-columns: 1.05fr 0.95fr;\n");
      out.write("            gap: 20px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .panel {\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            border-radius: 28px;\n");
      out.write("            background: rgba(3, 10, 28, 0.74);\n");
      out.write("            backdrop-filter: blur(26px) saturate(160%);\n");
      out.write("            -webkit-backdrop-filter: blur(26px) saturate(160%);\n");
      out.write("            box-shadow: 0 0 0 1px rgba(255,255,255,0.028) inset, var(--shadow);\n");
      out.write("            overflow: hidden;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        /* gradient border ring */\n");
      out.write("        .panel::before {\n");
      out.write("            content: \"\"; position: absolute; inset: -1px; border-radius: inherit; padding: 1px;\n");
      out.write("            background: linear-gradient(135deg, rgba(37,99,235,0.45), rgba(148,163,184,0.18) 45%, rgba(96,165,250,0.3) 100%);\n");
      out.write("            mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask-composite: xor; mask-composite: exclude; pointer-events: none;\n");
      out.write("            z-index: 0;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .left {\n");
      out.write("            padding: 36px;\n");
      out.write("            display: flex; flex-direction: column; justify-content: space-between; gap: 24px;\n");
      out.write("            position: relative; z-index: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* glow orb behind left panel */\n");
      out.write("        .left::after {\n");
      out.write("            content: \"\"; position: absolute; bottom: -80px; right: -80px;\n");
      out.write("            width: 360px; height: 360px;\n");
      out.write("            background: conic-gradient(from 200deg, rgba(37,99,235,0.28), rgba(96,165,250,0.22), rgba(203,213,225,0.14), rgba(37,99,235,0.28));\n");
      out.write("            border-radius: 50%; filter: blur(68px); opacity: 0.45;\n");
      out.write("            animation: float 13s ease-in-out infinite; pointer-events: none;\n");
      out.write("        }\n");
      out.write("        @keyframes float {\n");
      out.write("            0%, 100% { transform: translate3d(0,0,0) rotate(0deg); }\n");
      out.write("            50%       { transform: translate3d(-16px,-12px,0) rotate(5deg); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand-row { display: flex; align-items: center; gap: 14px; }\n");
      out.write("        .brand-badge {\n");
      out.write("            width: 50px; height: 50px; border-radius: 16px;\n");
      out.write("            display: grid; place-items: center;\n");
      out.write("            font-weight: 900; font-size: 14px; color: #fff;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            background: linear-gradient(145deg, var(--blue), var(--blue-light));\n");
      out.write("            box-shadow: 0 10px 28px rgba(37,99,235,0.5), 0 0 0 1px rgba(255,255,255,0.1) inset;\n");
      out.write("            position: relative; overflow: hidden; flex: 0 0 auto;\n");
      out.write("        }\n");
      out.write("        .brand-badge::after {\n");
      out.write("            content: \"\"; position: absolute; inset: 0;\n");
      out.write("            background: linear-gradient(135deg, transparent 0 35%, rgba(255,255,255,0.28) 36%, transparent 37% 100%);\n");
      out.write("            transform: translateX(-100%); animation: sheen 5s ease infinite;\n");
      out.write("        }\n");
      out.write("        @keyframes sheen {\n");
      out.write("            0% { transform: translateX(-100%); }\n");
      out.write("            28%, 100% { transform: translateX(220%); }\n");
      out.write("        }\n");
      out.write("        .brand-row strong {\n");
      out.write("            display: block; font-size: 18px; font-family: 'Poppins', sans-serif; font-weight: 800;\n");
      out.write("            background: var(--grad-text); -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("        .brand-row span { display: block; margin-top: 3px; color: var(--muted-dim); font-size: 12px; }\n");
      out.write("\n");
      out.write("        .hero { max-width: 640px; }\n");
      out.write("\n");
      out.write("        .eyebrow {\n");
      out.write("            display: inline-flex; align-items: center; gap: 10px;\n");
      out.write("            padding: 8px 14px; width: fit-content; border-radius: 999px;\n");
      out.write("            background: rgba(37,99,235,0.1);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.24);\n");
      out.write("            color: var(--blue-glow); font-size: 13px; font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .eyebrow i {\n");
      out.write("            width: 8px; height: 8px; border-radius: 999px;\n");
      out.write("            background: var(--silver-bright);\n");
      out.write("            box-shadow: 0 0 0 0 rgba(241,245,249,0.5);\n");
      out.write("            animation: pulse 2s infinite; flex: 0 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h1 {\n");
      out.write("            margin: 20px 0 0;\n");
      out.write("            font-size: clamp(38px, 4.8vw, 62px);\n");
      out.write("            line-height: 0.97; letter-spacing: -0.03em;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 800;\n");
      out.write("            background: var(--grad-text);\n");
      out.write("            background-size: 200% auto;\n");
      out.write("            -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("            animation: shine 9s linear infinite;\n");
      out.write("        }\n");
      out.write("        @keyframes shine { to { background-position: 200% center; } }\n");
      out.write("\n");
      out.write("        .hero p {\n");
      out.write("            margin: 16px 0 0; color: var(--muted); line-height: 1.78; font-size: 15px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .metrics {\n");
      out.write("            display: grid; grid-template-columns: repeat(2, minmax(0,1fr));\n");
      out.write("            gap: 12px; margin-top: 22px;\n");
      out.write("        }\n");
      out.write("        .metric {\n");
      out.write("            padding: 16px; border-radius: 20px;\n");
      out.write("            background: rgba(37,99,235,0.05);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.13);\n");
      out.write("            transition: transform .3s ease, border-color .3s ease;\n");
      out.write("        }\n");
      out.write("        .metric:hover { transform: translateY(-4px); border-color: rgba(96,165,250,0.35); }\n");
      out.write("        .metric span { display: block; color: var(--muted-dim); font-size: 12px; text-transform: uppercase; letter-spacing: 0.07em; font-weight: 500; }\n");
      out.write("        .metric strong {\n");
      out.write("            display: block; margin-top: 8px; font-size: 20px;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 700;\n");
      out.write("            background: linear-gradient(120deg, var(--silver), var(--blue-glow));\n");
      out.write("            -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ── RIGHT / AUTH ─────────────────────────────── */\n");
      out.write("        .auth-right {\n");
      out.write("            padding: 28px; display: flex; align-items: center;\n");
      out.write("            position: relative; z-index: 1;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .auth-card {\n");
      out.write("            width: 100%; padding: 32px; border-radius: 22px;\n");
      out.write("            background: rgba(2, 8, 22, 0.72);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.18);\n");
      out.write("            box-shadow: 0 16px 48px rgba(0,0,0,0.4), 0 0 0 1px rgba(255,255,255,0.025) inset;\n");
      out.write("            position: relative; overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .auth-card::before {\n");
      out.write("            content: \"\"; position: absolute; top: -60px; right: -60px;\n");
      out.write("            width: 200px; height: 200px;\n");
      out.write("            background: radial-gradient(circle, rgba(37,99,235,0.2), transparent 70%);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .auth-card h2 {\n");
      out.write("            margin: 0; font-size: 28px;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 700;\n");
      out.write("            background: var(--grad-text); -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("        .auth-card > p { margin: 10px 0 0; color: var(--muted); line-height: 1.7; font-size: 14px; }\n");
      out.write("\n");
      out.write("        .notice {\n");
      out.write("            margin-top: 18px; padding: 12px 16px; border-radius: 14px;\n");
      out.write("            border: 1px solid rgba(52,211,153,0.22);\n");
      out.write("            background: rgba(52,211,153,0.08);\n");
      out.write("            color: var(--success); font-size: 14px; font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .notice.error {\n");
      out.write("            border-color: rgba(248,113,113,0.22);\n");
      out.write("            background: rgba(248,113,113,0.08);\n");
      out.write("            color: var(--danger);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .form { display: grid; gap: 14px; margin-top: 24px; }\n");
      out.write("\n");
      out.write("        .field { display: grid; gap: 8px; }\n");
      out.write("        .field label {\n");
      out.write("            color: var(--silver-dim); font-size: 12px; font-weight: 600;\n");
      out.write("            text-transform: uppercase; letter-spacing: 0.07em;\n");
      out.write("        }\n");
      out.write("        .field input {\n");
      out.write("            width: 100%; min-height: 50px;\n");
      out.write("            border-radius: 14px; padding: 0 16px;\n");
      out.write("            border: 1px solid rgba(59,130,246,0.18);\n");
      out.write("            background: rgba(37,99,235,0.06);\n");
      out.write("            color: var(--text); outline: none; font-size: 15px;\n");
      out.write("            font-family: 'Inter', sans-serif;\n");
      out.write("            transition: border-color .2s ease, box-shadow .2s ease, background .2s ease;\n");
      out.write("        }\n");
      out.write("        .field input::placeholder { color: var(--muted-dim); }\n");
      out.write("        .field input:focus {\n");
      out.write("            border-color: rgba(96,165,250,0.6);\n");
      out.write("            background: rgba(37,99,235,0.1);\n");
      out.write("            box-shadow: 0 0 0 4px rgba(37,99,235,0.14), 0 0 20px rgba(37,99,235,0.1);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .button {\n");
      out.write("            display: inline-flex; align-items: center; justify-content: center;\n");
      out.write("            min-height: 50px; border: 0; border-radius: 14px; cursor: pointer;\n");
      out.write("            transition: transform .2s ease, box-shadow .2s ease;\n");
      out.write("            white-space: nowrap; font-weight: 600; font-size: 15px;\n");
      out.write("            font-family: 'Inter', sans-serif; position: relative; overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .button:hover { transform: translateY(-2px); }\n");
      out.write("        .button:active { transform: translateY(0); }\n");
      out.write("\n");
      out.write("        .button-primary {\n");
      out.write("            background: linear-gradient(135deg, var(--blue) 0%, var(--blue-light) 100%);\n");
      out.write("            color: #fff; width: 100%;\n");
      out.write("            box-shadow: 0 10px 28px rgba(37,99,235,0.42);\n");
      out.write("            border: 1px solid rgba(255,255,255,0.08);\n");
      out.write("        }\n");
      out.write("        .button-primary:hover {\n");
      out.write("            box-shadow: 0 14px 36px rgba(37,99,235,0.58);\n");
      out.write("        }\n");
      out.write("        .button-primary::after {\n");
      out.write("            content: \"\"; position: absolute; inset: 0;\n");
      out.write("            background: linear-gradient(105deg, transparent 30%, rgba(255,255,255,0.16) 50%, transparent 70%);\n");
      out.write("            transform: translateX(-100%); transition: transform .45s ease;\n");
      out.write("        }\n");
      out.write("        .button-primary:hover::after { transform: translateX(100%); }\n");
      out.write("\n");
      out.write("        .button-ghost {\n");
      out.write("            background: rgba(37,99,235,0.07);\n");
      out.write("            color: var(--silver); width: 100%;\n");
      out.write("            border: 1px solid rgba(59,130,246,0.22);\n");
      out.write("        }\n");
      out.write("        .button-ghost:hover {\n");
      out.write("            border-color: rgba(96,165,250,0.45);\n");
      out.write("            background: rgba(37,99,235,0.13);\n");
      out.write("            color: #fff;\n");
      out.write("            box-shadow: 0 0 22px rgba(37,99,235,0.15);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .action-row { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 14px; }\n");
      out.write("\n");
      out.write("        .micro { margin-top: 18px; color: var(--muted-dim); line-height: 1.7; font-size: 13px; }\n");
      out.write("        .micro a { color: var(--blue-glow); text-decoration: underline; text-underline-offset: 3px; }\n");
      out.write("        .micro a:hover { color: #fff; }\n");
      out.write("\n");
      out.write("        .feature-list { display: grid; gap: 10px; margin-top: 24px; }\n");
      out.write("        .feature {\n");
      out.write("            padding: 16px; border-radius: 16px;\n");
      out.write("            background: rgba(37,99,235,0.05);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.12);\n");
      out.write("            transition: transform .3s ease, border-color .3s ease, background .3s ease;\n");
      out.write("        }\n");
      out.write("        .feature:hover {\n");
      out.write("            transform: translateY(-3px);\n");
      out.write("            border-color: rgba(96,165,250,0.35);\n");
      out.write("            background: rgba(37,99,235,0.09);\n");
      out.write("        }\n");
      out.write("        .feature strong { display: block; margin-bottom: 6px; font-size: 14px; font-weight: 600; color: var(--silver-bright); }\n");
      out.write("        .feature span { color: var(--muted); font-size: 14px; line-height: 1.58; }\n");
      out.write("\n");
      out.write("        .pulse-bar {\n");
      out.write("            height: 3px; border-radius: 999px; margin-top: 20px;\n");
      out.write("            background: linear-gradient(90deg, var(--blue) 0%, var(--silver) 50%, var(--blue-light) 100%);\n");
      out.write("            background-size: 200% 100%;\n");
      out.write("            animation: sweep 2.8s linear infinite;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .pulse-bar::after {\n");
      out.write("            content: \"\"; position: absolute; inset: -3px; border-radius: 999px;\n");
      out.write("            background: inherit; filter: blur(5px); opacity: 0.5;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        @keyframes pulse {\n");
      out.write("            0%   { box-shadow: 0 0 0 0   rgba(241,245,249,0.55); }\n");
      out.write("            70%  { box-shadow: 0 0 0 10px rgba(241,245,249,0); }\n");
      out.write("            100% { box-shadow: 0 0 0 0   rgba(241,245,249,0); }\n");
      out.write("        }\n");
      out.write("        @keyframes sweep { from { background-position: 0 50%; } to { background-position: 200% 50%; } }\n");
      out.write("\n");
      out.write("        @media (max-width: 1040px) {\n");
      out.write("            .shell { grid-template-columns: 1fr; }\n");
      out.write("        }\n");
      out.write("        @media (max-width: 680px) {\n");
      out.write("            .page { padding: 12px; }\n");
      out.write("            .shell {\n");
      out.write("                min-height: auto;\n");
      out.write("                gap: 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .left {\n");
      out.write("                display: none;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .auth-right {\n");
      out.write("                padding: 0;\n");
      out.write("                align-items: stretch;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .auth-card {\n");
      out.write("                padding: 20px;\n");
      out.write("                border-radius: 22px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .auth-card h2 {\n");
      out.write("                font-size: 24px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .auth-card > p,\n");
      out.write("            .micro {\n");
      out.write("                font-size: 12px;\n");
      out.write("                line-height: 1.6;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .action-row {\n");
      out.write("                margin-top: 12px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .action-row .button {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .field input,\n");
      out.write("            .button {\n");
      out.write("                min-height: 48px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .metrics { grid-template-columns: 1fr; }\n");
      out.write("            .form { gap: 12px; margin-top: 18px; }\n");
      out.write("        }\n");
      out.write("        @media (prefers-reduced-motion: reduce) {\n");
      out.write("            *, *::before, *::after {\n");
      out.write("                animation-duration: 0.01ms !important;\n");
      out.write("                animation-iteration-count: 1 !important;\n");
      out.write("                transition-duration: 0.01ms !important;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<script>\n");
      out.write("    if (\"scrollRestoration\" in history) {\n");
      out.write("        history.scrollRestoration = \"manual\";\n");
      out.write("    }\n");
      out.write("    window.addEventListener(\"load\", function () {\n");
      out.write("        window.scrollTo(0, 0);\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<div class=\"page\">\n");
      out.write("    <div class=\"shell\">\n");
      out.write("        <section class=\"panel left\">\n");
      out.write("            <div>\n");
      out.write("                <div class=\"brand-row\">\n");
      out.write("                    <div class=\"brand-badge\">TC</div>\n");
      out.write("                    <div>\n");
      out.write("                        <strong>TeamConnect</strong>\n");
      out.write("                        <span>Secure team collaboration with real-time messaging</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"hero\">\n");
      out.write("                    <div class=\"eyebrow\"><i></i> Secure access to your workspace</div>\n");
      out.write("                    <h1>Welcome back to the conversation.</h1>\n");
      out.write("                    <p>\n");
      out.write("                        Log in to continue your threaded chat experience with fast contact switching, live polling,\n");
      out.write("                        and a clean dashboard that keeps the conversation in focus.\n");
      out.write("                    </p>\n");
      out.write("\n");
      out.write("                    <div class=\"metrics\">\n");
      out.write("                        <div class=\"metric\">\n");
      out.write("                            <span>Thread refresh</span>\n");
      out.write("                            <strong>Auto</strong>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"metric\">\n");
      out.write("                            <span>Interface style</span>\n");
      out.write("                            <strong>Glass</strong>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div>\n");
      out.write("                <div class=\"feature-list\">\n");
      out.write("                    <div class=\"feature\">\n");
      out.write("                        <strong>Professional session flow</strong>\n");
      out.write("                        <span>Jump from login into the dashboard without extra clutter or extra screens.</span>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"feature\">\n");
      out.write("                        <strong>Responsive by design</strong>\n");
      out.write("                        <span>The layout collapses cleanly on smaller screens and keeps the fields readable.</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"pulse-bar\"></div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <aside class=\"panel auth-right\">\n");
      out.write("            <div class=\"auth-card\">\n");
      out.write("                <h2>Login</h2>\n");
      out.write("                <p>Use your account details to open the chat dashboard.</p>\n");
      out.write("\n");
      out.write("                ");
 if (noticeText != null) { 
      out.write("\n");
      out.write("                <div class=\"notice ");
      out.print( ("1".equals(registered) || "1".equals(deleted)) ? "" : "error" );
      out.write('"');
      out.write('>');
      out.print( noticeText );
      out.write("</div>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <form class=\"form\" action=\"");
      out.print( contextPath );
      out.write("/login\" method=\"post\">\n");
      out.write("                    <div class=\"field\">\n");
      out.write("                        <label for=\"username\">Username</label>\n");
      out.write("                        <input id=\"username\" type=\"text\" name=\"username\" autocomplete=\"username\" required>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"field\">\n");
      out.write("                        <label for=\"password\">Password</label>\n");
      out.write("                        <input id=\"password\" type=\"password\" name=\"password\" autocomplete=\"current-password\" required>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <button class=\"button button-primary\" type=\"submit\">Login to Dashboard</button>\n");
      out.write("                </form>\n");
      out.write("\n");
      out.write("                <div class=\"action-row\">\n");
      out.write("                    <a class=\"button button-ghost\" href=\"");
      out.print( contextPath );
      out.write("/views/register.jsp\">Create account</a>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <p class=\"micro\">New here? <a href=\"");
      out.print( contextPath );
      out.write("/views/register.jsp\">Register now</a> and enter the workspace.</p>\n");
      out.write("            </div>\n");
      out.write("        </aside>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
