/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.23
 * Generated at: 2026-06-28 14:50:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    if (session != null && session.getAttribute("userId") != null) {
        response.sendRedirect(request.getContextPath() + "/chat");
        return;
    }

    String contextPath = request.getContextPath();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>TeamConnect</title>\n");
      out.write("    <style>\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&family=Inter:wght@300;400;500;600;700&display=swap');\n");
      out.write("\n");
      out.write("        :root {\n");
      out.write("            --bg:            #020818;\n");
      out.write("            --bg-2:          #030E22;\n");
      out.write("            --bg-3:          #041228;\n");
      out.write("            --text:          #F1F5F9;\n");
      out.write("            --muted:         #94A3B8;\n");
      out.write("            --muted-dim:     #64748B;\n");
      out.write("            --border:        rgba(59, 130, 246, 0.14);\n");
      out.write("            --shadow:        0 32px 80px rgba(0,0,0,0.7);\n");
      out.write("            --blue:          #2563EB;\n");
      out.write("            --blue-mid:      #3B82F6;\n");
      out.write("            --blue-light:    #60A5FA;\n");
      out.write("            --blue-glow:     #93C5FD;\n");
      out.write("            --silver:        #CBD5E1;\n");
      out.write("            --silver-dim:    #94A3B8;\n");
      out.write("            --silver-bright: #F1F5F9;\n");
      out.write("            --grad-primary:  linear-gradient(135deg, #2563EB, #60A5FA);\n");
      out.write("            --grad-silver:   linear-gradient(135deg, #94A3B8, #F1F5F9, #94A3B8);\n");
      out.write("            --grad-text:     linear-gradient(120deg, #F1F5F9 10%, #93C5FD 50%, #60A5FA 90%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        * { box-sizing: border-box; }\n");
      out.write("        html { scroll-behavior: smooth; }\n");
      out.write("        html, body {\n");
      out.write("            margin: 0; min-height: 100%;\n");
      out.write("            font-family: 'Inter', 'Segoe UI', Arial, sans-serif;\n");
      out.write("            color: var(--text);\n");
      out.write("            background: var(--bg);\n");
      out.write("            overflow-x: hidden;\n");
      out.write("            cursor: default;\n");
      out.write("        }\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            position: relative;\n");
      out.write("            background:\n");
      out.write("                    radial-gradient(ellipse 100% 65% at 5% -12%, rgba(37,99,235,0.28) 0%, transparent 55%),\n");
      out.write("                    radial-gradient(ellipse 75%  55% at 95%  8%, rgba(96,165,250,0.16) 0%, transparent 50%),\n");
      out.write("                    radial-gradient(ellipse 80%  55% at 50% 115%, rgba(59,130,246,0.12) 0%, transparent 55%),\n");
      out.write("                    linear-gradient(180deg, #020818 0%, #030D20 50%, #020818 100%);\n");
      out.write("        }\n");
      out.write("        a { color: inherit; text-decoration: none; }\n");
      out.write("\n");
      out.write("        /* Aurora */\n");
      out.write("        body::before {\n");
      out.write("            content: \"\"; position: fixed; inset: 0; z-index: 0; pointer-events: none;\n");
      out.write("            background:\n");
      out.write("                    radial-gradient(ellipse 700px 420px at 15% 25%, rgba(37,99,235,0.1)  0%, transparent 70%),\n");
      out.write("                    radial-gradient(ellipse 550px 380px at 85% 75%, rgba(96,165,250,0.08) 0%, transparent 70%),\n");
      out.write("                    radial-gradient(ellipse 400px 300px at 50% 50%, rgba(148,194,251,0.04) 0%, transparent 70%);\n");
      out.write("            animation: auroraShift 22s ease-in-out infinite alternate;\n");
      out.write("        }\n");
      out.write("        @keyframes auroraShift {\n");
      out.write("            0%   { transform: translate(0,0) scale(1); }\n");
      out.write("            50%  { transform: translate(-32px,20px) scale(1.06); }\n");
      out.write("            100% { transform: translate(24px,-30px) scale(0.97); }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* Grid */\n");
      out.write("        body::after {\n");
      out.write("            content: \"\"; position: fixed; inset: 0; z-index: 0; pointer-events: none;\n");
      out.write("            background-image:\n");
      out.write("                    linear-gradient(rgba(59,130,246,0.05) 1px, transparent 1px),\n");
      out.write("                    linear-gradient(90deg, rgba(59,130,246,0.05) 1px, transparent 1px);\n");
      out.write("            background-size: 70px 70px;\n");
      out.write("            mask-image: radial-gradient(ellipse 85% 75% at 50% 50%, black 15%, transparent 80%);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        canvas#fxCanvas { position: fixed; inset: 0; z-index: 0; pointer-events: none; opacity: 0.5; }\n");
      out.write("        .cursor-glow {\n");
      out.write("            position: fixed; width: 540px; height: 540px; border-radius: 50%;\n");
      out.write("            background: radial-gradient(circle, rgba(37,99,235,0.1), transparent 70%);\n");
      out.write("            pointer-events: none; z-index: 0; transform: translate(-50%,-50%);\n");
      out.write("            transition: left .22s ease, top .22s ease;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .wrap { width: min(1280px, calc(100% - 40px)); margin: 0 auto; position: relative; z-index: 1; }\n");
      out.write("        .page { min-height: 100vh; padding: 20px 0 72px; position: relative; overflow: hidden; }\n");
      out.write("\n");
      out.write("        /* ── TOPBAR ─────────────────────────────────── */\n");
      out.write("        .topbar {\n");
      out.write("            display: flex; align-items: center; justify-content: space-between; gap: 16px;\n");
      out.write("            padding: 14px 22px;\n");
      out.write("            border: 1px solid rgba(59,130,246,0.18);\n");
      out.write("            border-radius: 20px;\n");
      out.write("            background: rgba(2,8,24,0.78);\n");
      out.write("            backdrop-filter: blur(28px) saturate(180%);\n");
      out.write("            -webkit-backdrop-filter: blur(28px) saturate(180%);\n");
      out.write("            box-shadow: 0 0 0 1px rgba(255,255,255,0.04) inset, var(--shadow);\n");
      out.write("            position: sticky; top: 16px; z-index: 20;\n");
      out.write("            transition: padding .3s ease, background .3s ease, box-shadow .3s ease;\n");
      out.write("        }\n");
      out.write("        .topbar.scrolled {\n");
      out.write("            padding: 10px 22px;\n");
      out.write("            background: rgba(2,8,24,0.97);\n");
      out.write("            box-shadow: 0 8px 40px rgba(0,0,0,0.65), 0 0 0 1px rgba(59,130,246,0.14) inset;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .brand { display: flex; align-items: center; gap: 13px; min-width: 0; }\n");
      out.write("        .brand-mark {\n");
      out.write("            width: 48px; height: 48px; border-radius: 15px; display: grid; place-items: center;\n");
      out.write("            background: linear-gradient(145deg, var(--blue), var(--blue-light));\n");
      out.write("            color: #fff; font-weight: 900; font-size: 15px; font-family: 'Poppins', sans-serif;\n");
      out.write("            box-shadow: 0 8px 28px rgba(37,99,235,0.5), 0 0 0 1px rgba(255,255,255,0.1) inset;\n");
      out.write("            flex: 0 0 auto; position: relative; overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .brand-mark::after {\n");
      out.write("            content: \"\"; position: absolute; inset: 0;\n");
      out.write("            background: linear-gradient(135deg, transparent 0 35%, rgba(255,255,255,0.3) 36%, transparent 37% 100%);\n");
      out.write("            transform: translateX(-100%); animation: sheen 5s ease infinite;\n");
      out.write("        }\n");
      out.write("        @keyframes sheen {\n");
      out.write("            0% { transform: translateX(-100%); }\n");
      out.write("            30%, 100% { transform: translateX(220%); }\n");
      out.write("        }\n");
      out.write("        .brand-copy strong {\n");
      out.write("            display: block; font-size: 18px; line-height: 1.15;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 800;\n");
      out.write("            background: var(--grad-text);\n");
      out.write("            -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("        .brand-copy span { display: block; margin-top: 3px; color: var(--muted-dim); font-size: 12px; }\n");
      out.write("\n");
      out.write("        .nav { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; justify-content: flex-end; }\n");
      out.write("        .button {\n");
      out.write("            display: inline-flex; align-items: center; justify-content: center; min-height: 42px;\n");
      out.write("            padding: 0 20px; border-radius: 12px; border: 1px solid transparent;\n");
      out.write("            transition: transform .2s ease, box-shadow .2s ease, background .2s ease, border-color .2s ease;\n");
      out.write("            white-space: nowrap; font-weight: 600; font-size: 14px;\n");
      out.write("            font-family: 'Inter', sans-serif; cursor: pointer; position: relative; overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .button:hover { transform: translateY(-2px); }\n");
      out.write("        .button:active { transform: translateY(0); }\n");
      out.write("\n");
      out.write("        .button-ghost {\n");
      out.write("            background: rgba(59,130,246,0.06);\n");
      out.write("            border-color: rgba(59,130,246,0.22);\n");
      out.write("            color: var(--silver);\n");
      out.write("        }\n");
      out.write("        .button-ghost:hover {\n");
      out.write("            border-color: rgba(96,165,250,0.5);\n");
      out.write("            background: rgba(59,130,246,0.12);\n");
      out.write("            box-shadow: 0 0 24px rgba(37,99,235,0.15), 0 0 0 1px rgba(96,165,250,0.1) inset;\n");
      out.write("            color: #fff;\n");
      out.write("        }\n");
      out.write("        .button-primary {\n");
      out.write("            background: linear-gradient(135deg, var(--blue) 0%, var(--blue-light) 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            box-shadow: 0 8px 28px rgba(37,99,235,0.45);\n");
      out.write("            border-color: rgba(255,255,255,0.1);\n");
      out.write("        }\n");
      out.write("        .button-primary:hover {\n");
      out.write("            box-shadow: 0 14px 36px rgba(37,99,235,0.6), 0 0 0 1px rgba(255,255,255,0.12) inset;\n");
      out.write("        }\n");
      out.write("        /* silver shimmer on primary */\n");
      out.write("        .button-primary::after {\n");
      out.write("            content: \"\"; position: absolute; inset: 0;\n");
      out.write("            background: linear-gradient(105deg, transparent 30%, rgba(255,255,255,0.18) 50%, transparent 70%);\n");
      out.write("            transform: translateX(-100%);\n");
      out.write("            transition: transform .45s ease;\n");
      out.write("        }\n");
      out.write("        .button-primary:hover::after { transform: translateX(100%); }\n");
      out.write("\n");
      out.write("        /* ── HERO ────────────────────────────────────── */\n");
      out.write("        .hero { padding: 44px 0 32px; }\n");
      out.write("        .hero-grid { display: grid; grid-template-columns: 1.1fr 0.9fr; gap: 22px; align-items: stretch; }\n");
      out.write("\n");
      out.write("        .panel {\n");
      out.write("            border: 1px solid var(--border);\n");
      out.write("            border-radius: 28px;\n");
      out.write("            background: rgba(3,10,28,0.74);\n");
      out.write("            backdrop-filter: blur(26px) saturate(160%);\n");
      out.write("            -webkit-backdrop-filter: blur(26px) saturate(160%);\n");
      out.write("            box-shadow: 0 0 0 1px rgba(255,255,255,0.028) inset, var(--shadow);\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        /* gradient border ring */\n");
      out.write("        .panel::before {\n");
      out.write("            content: \"\"; position: absolute; inset: -1px; border-radius: inherit; padding: 1px;\n");
      out.write("            background: linear-gradient(135deg, rgba(37,99,235,0.45), rgba(148,163,184,0.18) 45%, rgba(96,165,250,0.3) 100%);\n");
      out.write("            mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask-composite: xor; mask-composite: exclude; pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .hero-main {\n");
      out.write("            padding: 42px; min-height: 645px;\n");
      out.write("            display: flex; flex-direction: column; justify-content: space-between; gap: 28px;\n");
      out.write("            overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .hero-main::after {\n");
      out.write("            content: \"\"; position: absolute; bottom: -100px; right: -100px;\n");
      out.write("            width: 420px; height: 420px;\n");
      out.write("            background: conic-gradient(from 200deg,\n");
      out.write("            rgba(37,99,235,0.32),\n");
      out.write("            rgba(96,165,250,0.28),\n");
      out.write("            rgba(203,213,225,0.18),\n");
      out.write("            rgba(37,99,235,0.32));\n");
      out.write("            border-radius: 50%; filter: blur(72px); opacity: 0.5;\n");
      out.write("            animation: float 13s ease-in-out infinite; pointer-events: none;\n");
      out.write("        }\n");
      out.write("        .hero-main::before {\n");
      out.write("            content: \"\"; position: absolute; inset: 22px; border-radius: 20px;\n");
      out.write("            background: linear-gradient(180deg, rgba(255,255,255,0.018), transparent 28%);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .badge {\n");
      out.write("            display: inline-flex; align-items: center; gap: 8px;\n");
      out.write("            padding: 8px 15px; border-radius: 999px;\n");
      out.write("            background: rgba(37,99,235,0.1); color: var(--blue-glow);\n");
      out.write("            font-size: 13px; width: fit-content;\n");
      out.write("            border: 1px solid rgba(59,130,246,0.24); font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .badge i {\n");
      out.write("            width: 8px; height: 8px; border-radius: 999px;\n");
      out.write("            background: var(--silver-bright);\n");
      out.write("            box-shadow: 0 0 0 0 rgba(241,245,249,0.5);\n");
      out.write("            animation: pulse 2s infinite; flex: 0 0 auto;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        h1 {\n");
      out.write("            margin: 22px 0 0;\n");
      out.write("            font-size: clamp(44px, 5.4vw, 82px);\n");
      out.write("            line-height: 0.94; letter-spacing: -0.035em;\n");
      out.write("            max-width: 13ch; text-wrap: balance;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 900;\n");
      out.write("            background: var(--grad-text);\n");
      out.write("            background-size: 200% auto;\n");
      out.write("            -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("            animation: shine 9s linear infinite;\n");
      out.write("        }\n");
      out.write("        @keyframes shine { to { background-position: 200% center; } }\n");
      out.write("\n");
      out.write("        .hero-copy {\n");
      out.write("            max-width: 640px; margin: 18px 0 0;\n");
      out.write("            color: var(--muted); font-size: 16px; line-height: 1.82;\n");
      out.write("        }\n");
      out.write("        .hero-copy strong, .section-text strong,\n");
      out.write("        .feature span strong, .timeline-item span strong { color: #fff; font-weight: 600; }\n");
      out.write("\n");
      out.write("        .hero-actions { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 30px; }\n");
      out.write("\n");
      out.write("        .hero-stats { display: grid; grid-template-columns: repeat(3, minmax(0,1fr)); gap: 12px; }\n");
      out.write("        .stat {\n");
      out.write("            padding: 18px; border-radius: 20px;\n");
      out.write("            background: rgba(37,99,235,0.05);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.13);\n");
      out.write("            transition: transform .3s ease, border-color .3s ease, box-shadow .3s ease;\n");
      out.write("        }\n");
      out.write("        .stat:hover {\n");
      out.write("            transform: translateY(-5px);\n");
      out.write("            border-color: rgba(96,165,250,0.4);\n");
      out.write("            box-shadow: 0 12px 42px rgba(37,99,235,0.14);\n");
      out.write("        }\n");
      out.write("        .stat span {\n");
      out.write("            display: block; color: var(--muted-dim); font-size: 11px;\n");
      out.write("            text-transform: uppercase; letter-spacing: 0.08em; font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .stat strong {\n");
      out.write("            display: block; margin-top: 8px; font-size: 22px;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 700;\n");
      out.write("            font-variant-numeric: tabular-nums;\n");
      out.write("            background: linear-gradient(120deg, var(--silver), var(--blue-glow));\n");
      out.write("            -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .side-stack { display: grid; gap: 22px; }\n");
      out.write("        .glass-box { padding: 28px; }\n");
      out.write("\n");
      out.write("        .section-title {\n");
      out.write("            margin: 0; font-size: 22px; line-height: 1.2;\n");
      out.write("            font-family: 'Poppins', sans-serif; font-weight: 700;\n");
      out.write("        }\n");
      out.write("        .section-text { margin: 12px 0 0; color: var(--muted); line-height: 1.76; font-size: 15px; }\n");
      out.write("        .section-subtle {\n");
      out.write("            display: inline-flex; align-items: center; gap: 8px;\n");
      out.write("            color: var(--blue-glow); font-size: 11px; margin-top: 8px;\n");
      out.write("            font-weight: 600; text-transform: uppercase; letter-spacing: 0.09em;\n");
      out.write("        }\n");
      out.write("        .section-subtle::before {\n");
      out.write("            content: \"\"; width: 32px; height: 1px;\n");
      out.write("            background: linear-gradient(90deg, rgba(96,165,250,0.9), transparent);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .feature-list { display: grid; gap: 10px; margin-top: 18px; }\n");
      out.write("        .feature {\n");
      out.write("            padding: 16px; border-radius: 16px;\n");
      out.write("            background: rgba(37,99,235,0.04);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.11);\n");
      out.write("            transition: transform .3s ease, border-color .3s ease, background .3s ease, box-shadow .3s ease;\n");
      out.write("        }\n");
      out.write("        .feature:hover {\n");
      out.write("            transform: translateY(-4px);\n");
      out.write("            border-color: rgba(96,165,250,0.4);\n");
      out.write("            background: rgba(37,99,235,0.08);\n");
      out.write("            box-shadow: 0 8px 32px rgba(37,99,235,0.12);\n");
      out.write("        }\n");
      out.write("        .feature strong { display: block; margin-bottom: 6px; font-size: 14px; font-weight: 600; color: var(--silver-bright); }\n");
      out.write("        .feature span { color: var(--muted); font-size: 14px; line-height: 1.62; }\n");
      out.write("\n");
      out.write("        /* ── STATUS CARD ──────────────────────────────── */\n");
      out.write("        .status-card {\n");
      out.write("            padding: 26px; border-radius: 26px;\n");
      out.write("            background:\n");
      out.write("                    linear-gradient(145deg, rgba(3,9,25,0.97), rgba(5,14,36,0.95)),\n");
      out.write("                    radial-gradient(ellipse 60% 50% at 90% 10%, rgba(37,99,235,0.18), transparent);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.2);\n");
      out.write("            box-shadow: 0 28px 70px rgba(0,0,0,0.55);\n");
      out.write("            position: relative; overflow: hidden;\n");
      out.write("        }\n");
      out.write("        .status-card::before {\n");
      out.write("            content: \"\"; position: absolute; inset: -1px; border-radius: inherit; padding: 1px;\n");
      out.write("            background: linear-gradient(135deg, rgba(37,99,235,0.65), rgba(148,163,184,0.25) 50%, rgba(96,165,250,0.55));\n");
      out.write("            mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask: linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0);\n");
      out.write("            -webkit-mask-composite: xor; mask-composite: exclude; pointer-events: none;\n");
      out.write("        }\n");
      out.write("        .status-card::after {\n");
      out.write("            content: \"\"; position: absolute; top: -70px; right: -70px;\n");
      out.write("            width: 240px; height: 240px;\n");
      out.write("            background: radial-gradient(circle, rgba(37,99,235,0.22), transparent 70%);\n");
      out.write("            pointer-events: none;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .status-top { display: flex; justify-content: space-between; gap: 10px; align-items: center; }\n");
      out.write("        .status-top span { opacity: 0.65; font-size: 12px; font-weight: 500; color: var(--silver-dim); }\n");
      out.write("        .status-top strong { font-size: 17px; font-weight: 700; font-family: 'Poppins', sans-serif; }\n");
      out.write("\n");
      out.write("        .pulse-bar {\n");
      out.write("            height: 3px; margin-top: 20px; border-radius: 999px;\n");
      out.write("            background: linear-gradient(90deg, var(--blue) 0%, var(--silver) 50%, var(--blue-light) 100%);\n");
      out.write("            background-size: 200% 100%;\n");
      out.write("            animation: sweep 2.8s linear infinite;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .pulse-bar::after {\n");
      out.write("            content: \"\"; position: absolute; inset: -3px; border-radius: 999px;\n");
      out.write("            background: inherit; filter: blur(5px); opacity: 0.55;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .meta-grid { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 12px; margin-top: 18px; }\n");
      out.write("        .meta {\n");
      out.write("            padding: 16px; border-radius: 16px;\n");
      out.write("            background: rgba(37,99,235,0.06);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.13);\n");
      out.write("        }\n");
      out.write("        .meta span {\n");
      out.write("            display: block; font-size: 11px; color: var(--muted-dim);\n");
      out.write("            text-transform: uppercase; letter-spacing: 0.08em; font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .meta strong { display: block; margin-top: 8px; font-size: 17px; font-weight: 700; font-family: 'Poppins', sans-serif; }\n");
      out.write("\n");
      out.write("        /* ── ABOUT ────────────────────────────────────── */\n");
      out.write("        .about { padding: 24px 0 0; }\n");
      out.write("        .section-head { display: flex; justify-content: space-between; align-items: end; gap: 16px; margin-bottom: 22px; }\n");
      out.write("        .section-head p { margin: 0; color: var(--muted); max-width: 680px; line-height: 1.76; font-size: 15px; }\n");
      out.write("\n");
      out.write("        .about-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 22px; }\n");
      out.write("        .about-card {\n");
      out.write("            padding: 32px; min-height: 300px; overflow: hidden;\n");
      out.write("            transition: transform .35s ease, box-shadow .35s ease;\n");
      out.write("        }\n");
      out.write("        .about-card:hover {\n");
      out.write("            transform: translateY(-6px);\n");
      out.write("            box-shadow: 0 40px 80px rgba(0,0,0,0.6), 0 0 0 1px rgba(59,130,246,0.22) inset;\n");
      out.write("        }\n");
      out.write("        .about-card::before { display: none; }\n");
      out.write("        .about-card h3 { margin: 0 0 12px; font-size: 18px; font-family: 'Poppins', sans-serif; font-weight: 700; }\n");
      out.write("        .about-card p { margin: 0; color: var(--muted); line-height: 1.76; font-size: 15px; }\n");
      out.write("\n");
      out.write("        .chips { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 18px; }\n");
      out.write("        .chip {\n");
      out.write("            padding: 7px 14px; border-radius: 999px;\n");
      out.write("            background: rgba(37,99,235,0.09);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.22);\n");
      out.write("            font-size: 13px; font-weight: 500; color: var(--blue-glow);\n");
      out.write("            transition: all .25s ease;\n");
      out.write("        }\n");
      out.write("        .chip:hover {\n");
      out.write("            border-color: rgba(96,165,250,0.55);\n");
      out.write("            background: rgba(37,99,235,0.18);\n");
      out.write("            color: var(--silver-bright);\n");
      out.write("            box-shadow: 0 0 14px rgba(37,99,235,0.18);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        .timeline { display: grid; gap: 0; margin-top: 18px; }\n");
      out.write("        .timeline-item {\n");
      out.write("            display: flex; gap: 14px; align-items: flex-start;\n");
      out.write("            padding: 14px 0; border-top: 1px solid rgba(59,130,246,0.1);\n");
      out.write("        }\n");
      out.write("        .timeline-item:first-child { border-top: 0; padding-top: 0; }\n");
      out.write("        .timeline-item b {\n");
      out.write("            min-width: 80px; color: var(--blue-glow); font-size: 12px;\n");
      out.write("            text-transform: uppercase; letter-spacing: 0.07em; font-weight: 600;\n");
      out.write("        }\n");
      out.write("        .timeline-item span { color: var(--muted); line-height: 1.65; font-size: 14px; }\n");
      out.write("\n");
      out.write("        .developer { display: flex; flex-direction: column; justify-content: space-between; }\n");
      out.write("        .developer strong {\n");
      out.write("            display: block; margin-top: 20px; font-size: 17px; font-weight: 700;\n");
      out.write("            font-family: 'Poppins', sans-serif;\n");
      out.write("            background: var(--grad-text); -webkit-background-clip: text; -webkit-text-fill-color: transparent;\n");
      out.write("        }\n");
      out.write("        .developer p { margin: 10px 0 0; color: var(--muted); line-height: 1.76; font-size: 15px; }\n");
      out.write("\n");
      out.write("        .spotlight { display: grid; gap: 10px; margin-top: 18px; }\n");
      out.write("        .spot-card {\n");
      out.write("            display: flex; align-items: center; justify-content: space-between; gap: 12px;\n");
      out.write("            padding: 14px 16px; border-radius: 16px;\n");
      out.write("            background: rgba(37,99,235,0.05);\n");
      out.write("            border: 1px solid rgba(59,130,246,0.12);\n");
      out.write("            transition: border-color .25s ease, background .25s ease, box-shadow .25s ease;\n");
      out.write("        }\n");
      out.write("        .spot-card:hover {\n");
      out.write("            border-color: rgba(96,165,250,0.35);\n");
      out.write("            background: rgba(37,99,235,0.09);\n");
      out.write("            box-shadow: 0 4px 24px rgba(37,99,235,0.1);\n");
      out.write("        }\n");
      out.write("        .spot-card em { font-style: normal; color: var(--muted-dim); font-size: 11px; text-transform: uppercase; letter-spacing: 0.07em; font-weight: 500; }\n");
      out.write("        .spot-card strong { display: block; font-size: 13px; font-weight: 600; margin: 4px 0 0; line-height: 1.4; }\n");
      out.write("\n");
      out.write("        .mini-bars { display: flex; align-items: end; gap: 3px; height: 22px; }\n");
      out.write("        .mini-bars span {\n");
      out.write("            width: 5px; border-radius: 999px;\n");
      out.write("            background: linear-gradient(180deg, var(--silver-bright), var(--blue-mid));\n");
      out.write("            animation: wave 1.6s ease-in-out infinite;\n");
      out.write("        }\n");
      out.write("        .mini-bars span:nth-child(1) { height: 10px; animation-delay: 0.00s; }\n");
      out.write("        .mini-bars span:nth-child(2) { height: 16px; animation-delay: 0.12s; }\n");
      out.write("        .mini-bars span:nth-child(3) { height: 20px; animation-delay: 0.24s; }\n");
      out.write("        .mini-bars span:nth-child(4) { height: 12px; animation-delay: 0.36s; }\n");
      out.write("        .mini-bars span:nth-child(5) { height: 18px; animation-delay: 0.48s; }\n");
      out.write("        .mini-bars span:nth-child(6) { height:  8px; animation-delay: 0.60s; }\n");
      out.write("\n");
      out.write("        /* ── REVEAL ───────────────────────────────────── */\n");
      out.write("        .reveal { opacity: 0; transform: translateY(32px); transition: opacity .9s cubic-bezier(.22,1,.36,1), transform .9s cubic-bezier(.22,1,.36,1); }\n");
      out.write("        .reveal.show { opacity: 1; transform: translateY(0); }\n");
      out.write("\n");
      out.write("        /* ── KEYFRAMES ────────────────────────────────── */\n");
      out.write("        @keyframes pulse {\n");
      out.write("            0%   { box-shadow: 0 0 0 0   rgba(241,245,249,0.55); }\n");
      out.write("            70%  { box-shadow: 0 0 0 10px rgba(241,245,249,0); }\n");
      out.write("            100% { box-shadow: 0 0 0 0   rgba(241,245,249,0); }\n");
      out.write("        }\n");
      out.write("        @keyframes sweep { from { background-position: 0 50%; } to { background-position: 200% 50%; } }\n");
      out.write("        @keyframes float {\n");
      out.write("            0%, 100% { transform: translate3d(0,0,0) rotate(0deg); }\n");
      out.write("            50%       { transform: translate3d(-18px,-14px,0) rotate(5deg); }\n");
      out.write("        }\n");
      out.write("        @keyframes wave {\n");
      out.write("            0%, 100% { transform: scaleY(0.45); opacity: 0.55; }\n");
      out.write("            50%       { transform: scaleY(1.45); opacity: 1; }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /* ── RESPONSIVE ───────────────────────────────── */\n");
      out.write("        @media (max-width: 1100px) {\n");
      out.write("            .hero-grid, .about-grid { grid-template-columns: 1fr; }\n");
      out.write("            .hero-main { min-height: auto; }\n");
      out.write("        }\n");
      out.write("        @media (max-width: 760px) {\n");
      out.write("            .wrap { width: calc(100% - 28px); }\n");
      out.write("            .topbar { flex-direction: column; align-items: stretch; }\n");
      out.write("            .nav { justify-content: flex-start; }\n");
      out.write("            .hero-main, .glass-box, .about-card { padding: 22px; }\n");
      out.write("            .hero-stats, .meta-grid { grid-template-columns: 1fr; }\n");
      out.write("            .section-head { flex-direction: column; align-items: flex-start; }\n");
      out.write("            .cursor-glow { display: none; }\n");
      out.write("            h1 { font-size: 40px; }\n");
      out.write("        }\n");
      out.write("        @media (prefers-reduced-motion: reduce) {\n");
      out.write("            *, *::before, *::after {\n");
      out.write("                animation-duration: 0.01ms !important;\n");
      out.write("                animation-iteration-count: 1 !important;\n");
      out.write("                transition-duration: 0.01ms !important;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<canvas id=\"fxCanvas\"></canvas>\n");
      out.write("<div class=\"cursor-glow\" id=\"glow\"></div>\n");
      out.write("\n");
      out.write("<div class=\"page\">\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("        <header class=\"topbar\" id=\"topbar\">\n");
      out.write("            <div class=\"brand\">\n");
      out.write("                <div class=\"brand-mark\">TC</div>\n");
      out.write("                <div class=\"brand-copy\">\n");
      out.write("                    <strong>TeamConnect</strong>\n");
      out.write("                    <span>Secure team collaboration with real-time messaging</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <nav class=\"nav\">\n");
      out.write("                <a href=\"#about\" class=\"button button-ghost\">About</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/views/login.jsp\" class=\"button button-ghost\">Login</a>\n");
      out.write("                <a href=\"");
      out.print( contextPath );
      out.write("/views/register.jsp\" class=\"button button-primary\">Get Started</a>\n");
      out.write("            </nav>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <main class=\"hero\">\n");
      out.write("            <div class=\"hero-grid\">\n");
      out.write("                <section class=\"panel hero-main reveal\">\n");
      out.write("                    <div>\n");
      out.write("                        <div class=\"badge\"><i></i> Real-time messaging platform for instant conversations</div>\n");
      out.write("                        <h1>Chat smarter. Connect faster.</h1>\n");
      out.write("                        <p class=\"hero-copy\">\n");
      out.write("                            TeamConnect is a complete messaging platform built with JSP and Servlet technology.\n");
      out.write("                            Create an account, add contacts, and start chatting instantly with live message delivery,\n");
      out.write("                            photo and file sharing, searchable chat history, and a dashboard that keeps every\n");
      out.write("                            conversation organized in one place.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"hero-actions\">\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/views/login.jsp\" class=\"button button-primary\">Login to Dashboard</a>\n");
      out.write("                            <a href=\"");
      out.print( contextPath );
      out.write("/views/register.jsp\" class=\"button button-ghost\">Create Account</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"hero-stats\">\n");
      out.write("                        <div class=\"stat\">\n");
      out.write("                            <span>Threaded chat</span>\n");
      out.write("                            <strong id=\"statSync\">Live sync</strong>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat\">\n");
      out.write("                            <span>Attachments</span>\n");
      out.write("                            <strong>Files + Photos</strong>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"stat\">\n");
      out.write("                            <span>History</span>\n");
      out.write("                            <strong>Searchable</strong>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("                <aside class=\"side-stack\">\n");
      out.write("                    <section class=\"panel glass-box reveal\">\n");
      out.write("                        <h2 class=\"section-title\">What it does</h2>\n");
      out.write("                        <div class=\"section-subtle\">Core features at a glance</div>\n");
      out.write("                        <p class=\"section-text\">\n");
      out.write("                            Every account gets a personal dashboard to manage contacts, view active conversations,\n");
      out.write("                            and send messages in real time. Conversations stay synced automatically, so you always\n");
      out.write("                            see the latest reply without refreshing the page.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"feature-list\">\n");
      out.write("                            <div class=\"feature\">\n");
      out.write("                                <strong>Live messaging</strong>\n");
      out.write("                                <span>Messages are delivered and updated instantly, with read status and timestamps for every conversation.</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature\">\n");
      out.write("                                <strong>Photo &amp; file sharing</strong>\n");
      out.write("                                <span>Send images and documents directly inside a chat thread without switching tools or tabs.</span>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"feature\">\n");
      out.write("                                <strong>Searchable history</strong>\n");
      out.write("                                <span>Find any past message or shared file quickly using built-in conversation search.</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("\n");
      out.write("                    <section class=\"status-card reveal\">\n");
      out.write("                        <div class=\"status-top\">\n");
      out.write("                            <div>\n");
      out.write("                                <span>System status</span>\n");
      out.write("                                <strong>Online and ready</strong>\n");
      out.write("                            </div>\n");
      out.write("                            <span>JSP + Servlet + MySQL</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"pulse-bar\"></div>\n");
      out.write("                        <div class=\"spotlight\">\n");
      out.write("                            <div class=\"spot-card\">\n");
      out.write("                                <div>\n");
      out.write("                                    <em>Account security</em>\n");
      out.write("                                    <strong>Encrypted login with session-based access control</strong>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"mini-bars\" aria-hidden=\"true\">\n");
      out.write("                                    <span></span><span></span><span></span><span></span><span></span><span></span>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"spot-card\">\n");
      out.write("                                <div>\n");
      out.write("                                    <em>Storage</em>\n");
      out.write("                                    <strong>Messages and files backed by a MySQL database</strong>\n");
      out.write("                                </div>\n");
      out.write("                                <span class=\"button button-ghost\" style=\"min-height:34px;padding:0 12px;\">Reliable</span>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"meta-grid\">\n");
      out.write("                            <div class=\"meta\">\n");
      out.write("                                <span>Devices</span>\n");
      out.write("                                <strong>Mobile &amp; Desktop</strong>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"meta\">\n");
      out.write("                                <span>Login</span>\n");
      out.write("                                <strong>Secure</strong>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </section>\n");
      out.write("                </aside>\n");
      out.write("            </div>\n");
      out.write("        </main>\n");
      out.write("\n");
      out.write("        <section class=\"about\" id=\"about\">\n");
      out.write("            <div class=\"section-head reveal\">\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"badge\"><i></i> About TeamConnect</div>\n");
      out.write("                    <h2 class=\"section-title\" style=\"margin-top:12px;\">A complete messaging platform, built end to end</h2>\n");
      out.write("                </div>\n");
      out.write("                <p>\n");
      out.write("                    TeamConnect covers everything a real chat application needs — secure registration and\n");
      out.write("                    login, a contact list, real-time conversations, file sharing, and an admin-friendly structure\n");
      out.write("                    that's easy to extend. Built and maintained by Abhishek Samadhiya.\n");
      out.write("                </p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"about-grid\">\n");
      out.write("                <section class=\"panel about-card developer reveal\">\n");
      out.write("                    <div>\n");
      out.write("                        <h3>Developer profile</h3>\n");
      out.write("                        <p>\n");
      out.write("                            Abhishek Samadhiya built TeamConnect with JSP and Servlet technology. The goal\n");
      out.write("                            is a modern workspace with clear conversation hierarchy, strong visual separation, and a\n");
      out.write("                            presentation that feels deliberate rather than generic.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"chips\">\n");
      out.write("                            <span class=\"chip\">JSP</span>\n");
      out.write("                            <span class=\"chip\">Servlet</span>\n");
      out.write("                            <span class=\"chip\">MySQL</span>\n");
      out.write("                            <span class=\"chip\">File Sharing</span>\n");
      out.write("                            <span class=\"chip\">Secure UI</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <strong>Abhishek Samadhiya</strong>\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("                <section class=\"panel about-card reveal\">\n");
      out.write("                    <h3>Project focus</h3>\n");
      out.write("                    <div class=\"timeline\">\n");
      out.write("                        <div class=\"timeline-item\">\n");
      out.write("                            <b>Design</b>\n");
      out.write("                            <span>Electric blue and silver on deep navy — a palette that feels corporate-premium, like Microsoft Fluent meets Linear.</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"timeline-item\">\n");
      out.write("                            <b>Workflow</b>\n");
      out.write("                            <span>Dashboard-first layout, message history search, and attachment sharing in one clean flow.</span>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"timeline-item\">\n");
      out.write("                            <b>Motion</b>\n");
      out.write("                            <span>Layered glass, silver-blue glow edges, drifting particles, and animated accents create a dynamic impression without breaking readability.</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    var canvas = document.getElementById('fxCanvas');\n");
      out.write("    var ctx = canvas.getContext('2d');\n");
      out.write("    var particles = [];\n");
      out.write("    var count = 60;\n");
      out.write("    function resize(){ canvas.width = window.innerWidth; canvas.height = window.innerHeight; }\n");
      out.write("    resize();\n");
      out.write("    window.addEventListener('resize', resize);\n");
      out.write("    function Particle(){\n");
      out.write("        this.x = Math.random() * canvas.width;\n");
      out.write("        this.y = Math.random() * canvas.height;\n");
      out.write("        this.r = Math.random() * 1.6 + 0.4;\n");
      out.write("        this.vx = (Math.random() - 0.5) * 0.25;\n");
      out.write("        this.vy = (Math.random() - 0.5) * 0.25;\n");
      out.write("        this.hue = Math.random() > 0.5 ? '59,130,246' : '203,213,225';\n");
      out.write("        this.alpha = Math.random() * 0.45 + 0.15;\n");
      out.write("    }\n");
      out.write("    for(var i=0;i<count;i++){ particles.push(new Particle()); }\n");
      out.write("    function loop(){\n");
      out.write("        ctx.clearRect(0,0,canvas.width,canvas.height);\n");
      out.write("        for(var i=0;i<particles.length;i++){\n");
      out.write("            var p = particles[i];\n");
      out.write("            p.x += p.vx; p.y += p.vy;\n");
      out.write("            if(p.x<0) p.x=canvas.width; if(p.x>canvas.width) p.x=0;\n");
      out.write("            if(p.y<0) p.y=canvas.height; if(p.y>canvas.height) p.y=0;\n");
      out.write("            ctx.beginPath();\n");
      out.write("            ctx.arc(p.x,p.y,p.r,0,Math.PI*2);\n");
      out.write("            ctx.fillStyle='rgba('+p.hue+','+p.alpha+')';\n");
      out.write("            ctx.fill();\n");
      out.write("        }\n");
      out.write("        for(var a=0;a<particles.length;a++){\n");
      out.write("            for(var b=a+1;b<particles.length;b++){\n");
      out.write("                var dx=particles[a].x-particles[b].x;\n");
      out.write("                var dy=particles[a].y-particles[b].y;\n");
      out.write("                var dist=Math.sqrt(dx*dx+dy*dy);\n");
      out.write("                if(dist<100){\n");
      out.write("                    ctx.beginPath();\n");
      out.write("                    ctx.moveTo(particles[a].x,particles[a].y);\n");
      out.write("                    ctx.lineTo(particles[b].x,particles[b].y);\n");
      out.write("                    ctx.strokeStyle='rgba(96,165,250,'+(0.1*(1-dist/100))+')';\n");
      out.write("                    ctx.lineWidth=1;\n");
      out.write("                    ctx.stroke();\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        requestAnimationFrame(loop);\n");
      out.write("    }\n");
      out.write("    loop();\n");
      out.write("\n");
      out.write("    var glow = document.getElementById('glow');\n");
      out.write("    document.addEventListener('mousemove', function(e){\n");
      out.write("        glow.style.left = e.clientX+'px';\n");
      out.write("        glow.style.top  = e.clientY+'px';\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var topbar = document.getElementById('topbar');\n");
      out.write("    window.addEventListener('scroll', function(){\n");
      out.write("        if(window.scrollY>30){ topbar.classList.add('scrolled'); }\n");
      out.write("        else { topbar.classList.remove('scrolled'); }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var reveals = document.querySelectorAll('.reveal');\n");
      out.write("    var observer = new IntersectionObserver(function(entries){\n");
      out.write("        entries.forEach(function(entry){\n");
      out.write("            if(entry.isIntersecting){ entry.target.classList.add('show'); }\n");
      out.write("        });\n");
      out.write("    },{ threshold: 0.12 });\n");
      out.write("    reveals.forEach(function(el){ observer.observe(el); });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
